### ISSUE TITLE
Allow encrypted master-master replication

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea-appliance#21]
Right now, the MySQL traffic between two masters is unencrypted. The replication setup tool should make it possible to configure encryption, e.g. using a tinc tunnel.

**Comment by cornelinux** [comment]
We could think of identifying free networks. Then we suggest three free networks to the administrator.

We could either use ``ping`` (lightweight) or ``nmap`` (reliable).

E.g. we would like to check the network 192.168.2.0/30, then we could run

    ping 192.168.2.1
    ping 192.168.2.2
    ping 192.168.2.3

or

    nmap -sP -oX .... 192.168.2.0/24

We might have a list of networks, which we check.
We also allow the adminsitrator to define a network manually.
Then the administrator can choose between networks that were checked successfully (did not respond)

     Which network do you want to use as transfer network?

     ( ) 192.168.2.0/30
     ( ) 10.2.2.10/30
     (*) 172.16.16.0/30
     ( ) choose your own

**Comment by fredreichbier** [comment]
Sounds good! And then we would build a simple tinc tunnel using that network?

**Comment by cornelinux** [comment]
Could be tinc or anything else ;-)

**Comment by cornelinux** [comment]
Here is a nice write up on how to setup tinc between two nodes:

https://linode.com/docs/networking/vpn/how-to-set-up-tinc-peer-to-peer-vpn/

**Comment by cornelinux** [comment]
I would drop the network scanning in the first place.
I would simply add a longer description: "Choose a network range, that is not used!"
And give some examples like 10.177.177.76/30.

We can use the package ``python-ipcalc``. https://pypi.python.org/pypi/ipcalc

This way we simply now the host ip addresses: 

    for x in ipcalc.Network("10.177.177.76/30")

# Config values

Name of the network: "privacyideaVPN"
Name of the nodes: "node1", "node2"

=> tinc.conf looks like:

    Name = privacyideaVPN
    ConnectTo = node2 # (or node1)

We choose a key size of 4096 bit:

    tincd -n privacyideaVPN -K 4096
