### ISSUE TITLE
Backup does not contain enckey

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea-appliance#22]
Contrary to the docstring of ``Backup.backup_now``, the manually created backup file does not contain the enckey. This is also true for the backup files created by the cronjob.

**Comment by cornelinux** [comment]
As ``backup_now`` simply calls the ``pi-manage`` command we should not change the pi-manage command here. pi-manage does not add the enckey, just as the help tells us.

<pre>
usage: Create database backup and restore

Create database backup and restore

positional arguments:
  {restore,create}
    restore         Restore a previously made backup. You need to specify the
                    tgz file.
    create          Create a new backup of the database and the configuration.
                    The default does not include the encryption key. Use the
                    'enckey' option to also backup the encryption key. Then
                    you should make sure, that the backups are stored safely.

optional arguments:
</pre>

So I guess we should "fix" the docstring of ``Backup.backup_now``.

**Comment by fredreichbier** [comment]
Either that or we change the ``pi-manage`` call to include the ``-e`` option which includes the enckey. What makes the most sense for the user?

**Comment by cornelinux** [comment]
I would think with the appliance the backup directory contains some kind of snapshots of the database for rollback.
For this scenario, we do not need the encryption key.

I tend to think that the user/administrator should manualy/initially backup the encryption key outside of the appliance.

**Comment by fredreichbier** [comment]
Sounds good! I changed the docstring accordingly and added some notes that the encryption key is not part of the backup.
