### ISSUE TITLE
Backup permission problem

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea-appliance#23]
``pi-manage backup create`` creates the directory ``/var/lib/privacyidea/backup``, if it does not exist yet, and writes to the file ``/etc/privacyidea/mysql.cnf``.
However, this causes problems in the following scenario. Consider
* We haven't done any backups yet.
* We manually create a backup using the appliance tool, which we run as root. This creates ``/etc/privacyidea/mysql.cnf`` and ``/var/lib/privacyidea/backup``, both owned by root.
* We add an automatic backup job using the appliance tool.

The automatic backup will always fail, because it is run as ``privacyidea``, which is not allowed to write to ``/etc/privacyidea/mysql.cnf`` and ``/var/lib/privacyidea/backup``.

**Comment by cornelinux** [comment]
# A

So I guess ``pi-manage backup create`` needs to set the owner to *privacyidea* a.k.a. the owner of the directory */etc/privacyidea/mysql.cnf*.
But we need to fix this in ``pi-manage``, which is called by ``backup_now``.

# B

We only fix ``backup_now``. But in this case we still have problems, if the root calls ``pi-manage backup create`` from the command line. Then the file *my.cnf* will be created with root rights.
Thus - I prefer A.

**Comment by fredreichbier** [comment]
Or we run the cronjob as root -- but I guess that's not really desirable.
I'll send a PR for A later today.

**Comment by fredreichbier** [comment]
May there be users who have already done backups manually as root using ``pi-manage backup create`` and now use the appliance tool to schedule automatic backups?
For these, we could implement a safeguard: When the appliance enables automatic backups, it checks whether ``/var/lib/privacyidea/backup`` and ``/etc/privacyidea/mysql.cnf`` already exist and sets the correct permissions if this is the case.

**Comment by cornelinux** [comment]
Thx!
