### ISSUE TITLE
Integrate LDAP proxy

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea-appliance#28]
Make it possible to configure the [LDAP proxy](https://github.com/NetKnights-GmbH/privacyidea-ldap-proxy).

**Comment by fredreichbier** [comment]
In this context, it would be pretty cool to have a configuration wizard.

**Comment by fredreichbier** [comment]
[28/ldap-proxy](https://github.com/privacyidea/privacyidea-appliance/tree/28/ldap-proxy) works so far! What's still missing is:
* an option to restart the LDAP proxy. I guess this makes most sense to implement when we have built some Ubuntu package.
* options to configure the bind and app cache

**Comment by cornelinux** [comment]
Yes, I need to build ubuntu packates, so that we can also easily use the ldap proxy in our environment! ;-)
