### ISSUE TITLE
Add MySQL Master Master replication

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-appliance#8]
https://www.digitalocean.com/community/tutorials/how-to-set-up-mysql-master-master-replication

http://www.chrislondon.co/mysql-auto-increment-replication/

https://www.howtoforge.de/anleitung/einrichten-von-master-master-replikation-mit-mysql-5-auf-debian-etch/

**Comment by cornelinux** [comment]
We only need the other machines IP address and root password.

First we should check

* Is mysql installed
* Is privacyIDEA installed

Then we need to:

1. Then we can configure/change the the my.cnf files and
2. set the clients in mysql.

**Comment by cornelinux** [comment]
# TODO

1. Replication tinc tunnel
2. tidy up code

**Comment by fredreichbier** [comment]
Basic master-master replication works now. I've opened #21 for the encryption support.
